// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAp6ahJaO-yjT_kC_cGlSaAe546y7xENU',
    appId: '1:947437698517:web:d090e34d46533ce6d5115c',
    messagingSenderId: '947437698517',
    projectId: 'tlego-b7ed1',
    authDomain: 'tlego-b7ed1.firebaseapp.com',
    storageBucket: 'tlego-b7ed1.firebasestorage.app',
    measurementId: 'G-FRXYJ0BFG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjNG7oWmchluOcfJ6DNB3InhQf7ozAas',
    appId: '1:947437698517:android:0e75d3aa9dd8ec51d5115c',
    messagingSenderId: '947437698517',
    projectId: 'tlego-b7ed1',
    storageBucket: 'tlego-b7ed1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4etYijsSZnQm-bU9wWdVAyYaNJHdV98M',
    appId: '1:947437698517:ios:8e65acf9e9b612ced5115c',
    messagingSenderId: '947437698517',
    projectId: 'tlego-b7ed1',
    storageBucket: 'tlego-b7ed1.firebasestorage.app',
    iosBundleId: 'com.example.tlegoWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4etYijsSZnQm-bU9wWdVAyYaNJHdV98M',
    appId: '1:947437698517:ios:8e65acf9e9b612ced5115c',
    messagingSenderId: '947437698517',
    projectId: 'tlego-b7ed1',
    storageBucket: 'tlego-b7ed1.firebasestorage.app',
    iosBundleId: 'com.example.tlegoWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAp6ahJaO-yjT_kC_cGlSaAe546y7xENU',
    appId: '1:947437698517:web:37b92678541b43c0d5115c',
    messagingSenderId: '947437698517',
    projectId: 'tlego-b7ed1',
    authDomain: 'tlego-b7ed1.firebaseapp.com',
    storageBucket: 'tlego-b7ed1.firebasestorage.app',
    measurementId: 'G-T19R5640P7',
  );
}
